/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-08-02 22:31:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.onLineTest;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Map;

public final class reGoTest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- \r\n");
      out.write("쿠키 만들기\r\n");
      out.write("// 세션 쿠키 생성 - 브라우저를 닫으면 없으집니다. $.cookie('name', 'value'); \r\n");
      out.write("// 7일 뒤에 만료되는 쿠키 생성 $.cookie('name', 'value', { expires: 7 }); \r\n");
      out.write("// 전체 사이트에 대해 7일 뒤에 만료되는 쿠키 생성 $.cookie('name', 'value', { expires: 7, path: '/' });\r\n");
      out.write("// 세션 쿠키 생성 - 브라우저를 닫으면 없으집니다. $.cookie('name', 'value'); \r\n");
      out.write("// 7일 뒤에 만료되는 쿠키 생성 $.cookie('name', 'value', { expires: 7 }); \r\n");
      out.write("// 전체 사이트에 대해 7일 뒤에 만료되는 쿠키 생성 $.cookie('name', 'value', { expires: 7, path: '/' });\r\n");
      out.write("\r\n");
      out.write("쿠키 읽기\r\n");
      out.write("// 키로 사용한 이름으로 값을 읽습니다. \r\n");
      out.write("// 키로 저장된 값이 없으면 undefined 가 반환됩니다. $.cookie('name'); \r\n");
      out.write("// 모든 쿠키 읽기 // 모든 쿠키를 { \"name\": \"value\" } 형태의 객체로 반환합니다. $.cookie();\r\n");
      out.write("\r\n");
      out.write("쿠키 삭제하기\r\n");
      out.write("// 성공적으로 삭제되면 true 를 반환하고, 삭제 못했을때는 false를 반환합니다. \r\n");
      out.write("$.removeCookie('name'); // 쿠키 삭제시 생성할때 와 같은 path와 domain 을 사용해야 합니다. \r\n");
      out.write("// 아래와 같이 생성했다면, $.cookie('name', 'value', { path: '/' }); \r\n");
      out.write("// 이렇게 삭제할 수 없습니다. $.removeCookie('name'); // => false \r\n");
      out.write("// 이렇게 삭제해야 합니다. $.removeCookie('name', { path: '/' }); // => true\r\n");
      out.write(" -->    \r\n");

	Map<String,Object> pMap = (Map<String,Object>)session.getAttribute("pMap");
	String s_memid = "";
	String s_memname = "";
	if(pMap!=null){
		s_memid = pMap.get("mem_id").toString();
		s_memname = pMap.get("mem_name").toString();
	}
	//out.print("이름:"+s_memname);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Basic Window - jQuery EasyUI Demo</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \tvar g_subcd;\r\n");
      out.write("\t\tvar r_isOk='';\r\n");
      out.write("    \tfunction examSend(){\r\n");
      out.write("    \t\t//alert(\"1번 답안:\"+$.cookie('c_test1'));\r\n");
      out.write("    \t\t//alert(\"2번 답안:\"+$.cookie('c_test2'));\r\n");
      out.write("    \t\t//alert(\"3번 답안:\"+$.cookie('c_test3'));\r\n");
      out.write("    \t\t//alert(\"4번 답안:\"+$.cookie('c_test4'));\r\n");
      out.write("    \t\t//alert(\"콤보배열길이:\"+document.getElementById(\"f_test1\").cb.length);\r\n");
      out.write("    \t\tvar dap1 = $.cookie('c_test1');\r\n");
      out.write("    \t\tvar dap2 = $.cookie('c_test2');\r\n");
      out.write("    \t\tvar dap3 = $.cookie('c_test3');\r\n");
      out.write("    \t\tvar dap4 = $.cookie('c_test4');\r\n");
      out.write("    \t\tvar exam_no=$(\"#exam_no\").val();\r\n");
      out.write("    \t\talert(exam_no);\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\tmethod:\"get\"\r\n");
      out.write("    \t\t   ,url:\"examPaperAdd.kos?work=onLineTest&exam_no=\"+exam_no+\"&dap1=\"+dap1+\"&dap2=\"+dap2+\"&dap3=\"+dap3+\"&dap4=\"+dap4\r\n");
      out.write("    \t\t   ,success:function(data){\r\n");
      out.write("    \t\t\t   alert(data);\r\n");
      out.write("    \t\t   }\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\t$.removeCookie('c_test1');\r\n");
      out.write("    \t\t$.removeCookie('c_test2');\r\n");
      out.write("    \t\t$.removeCookie('c_test3');\r\n");
      out.write("    \t\t$.removeCookie('c_test4');\r\n");
      out.write("    \t\t$(\"#dlg_send\").dialog('close');\r\n");
      out.write("    \t}  \t\r\n");
      out.write("    \tfunction answer(p_dap,num){//p_dap변수 1,2,3,4\r\n");
      out.write("    \t\t//브라우저가 돔구성시 같은 이름이면 자동으로 배열전환\r\n");
      out.write("    \t\tfor(var i=0;i<document.getElementById(\"f_test\"+num).cb.length;i++){\r\n");
      out.write("    \t\t\tif(p_dap==i){\r\n");
      out.write("    \t\t\t\tdocument.getElementById(\"f_test\"+num).cb[i].checked=1;\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\telse{\r\n");
      out.write("    \t\t\t\tdocument.getElementById(\"f_test\"+num).cb[i].checked=0;\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction examStart(){\r\n");
      out.write("    \t\t$(\"#d_isOk\").html(\"\");\r\n");
      out.write("    \t\tvar u_exam_no = $(\"#exam_no\").val();\r\n");
      out.write("    \t\t$.ajax({\r\n");
      out.write("    \t\t\tmethod:\"get\"\r\n");
      out.write("    \t\t   ,url:\"isOk.kos?work=onLineTest&mem_id=");
      out.print(s_memid);
      out.write("&exam_no=\"+u_exam_no\r\n");
      out.write("    \t\t   ,success:function(result){\r\n");
      out.write("    \t\t\t   //alert(\"result: \"+result);\r\n");
      out.write("    \t\t\t   if(\"승인\"==result){\r\n");
      out.write("    \t\t\t\t    $(\"#d_isOk\").html(\"\");\r\n");
      out.write("    \t        \t\t$.ajax({\r\n");
      out.write("    \t        \t\t\tmethod:\"get\"\r\n");
      out.write("    \t        \t\t   ,url:\"swDesignExam.kos?work=onLineTest&sub_cd=\"+g_subcd\r\n");
      out.write("    \t        \t\t   ,success:function(result){\r\n");
      out.write("    \t        \t\t\t   //alert(\"result:\"+result);\r\n");
      out.write("    \t        \t\t       //var result1 = JSON.stringify(result);\r\n");
      out.write("    \t        \t\t       var jsonDoc = JSON.parse(result);\r\n");
      out.write("    \t    /*     \t\t       var obj = JSON.parse(result, function(key, value){\r\n");
      out.write("    \t        \t\t    \t  if(key==\"question\"){\r\n");
      out.write("    \t        \t\t    \t\t  alert(\"key:\"+key+\", value:\"+value);\r\n");
      out.write("    \t        \t\t    \t  }else{\r\n");
      out.write("    \t        \t\t    \t\t  alert(\"없을 때\");\r\n");
      out.write("    \t        \t\t    \t  }\r\n");
      out.write("    \t        \t\t       }); */\r\n");
      out.write("    \t        \t\t       if(jsonDoc.length>0){//추천 테마 있음\r\n");
      out.write("    \t        \t\t       \t   //for(var i=0; i<jsonDoc.length; i++){\r\n");
      out.write("    \t        \t\t        \t  //alert(\"question:\"+jsonDoc[i].question+\", answer1:\"+jsonDoc[i].answer1);\r\n");
      out.write("    \t    \t\t\t\t\t  \t    var v_test1 = \"\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t    var v_test2 = \"\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t    var v_test3 = \"\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t    var v_test4 = \"\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test1+=\"<form id='f_test1'>\"\r\n");
      out.write("    \t        \t\t        \t  v_test1+=jsonDoc[0].d_no+\". \"+jsonDoc[0].question+\"<br/><br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,1)'>\"+jsonDoc[0].answer1+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,1)'>\"+jsonDoc[0].answer2+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,1)'>\"+jsonDoc[0].answer3+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,1)'>\"+jsonDoc[0].answer4+\"<br/>\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test1+=\"</form>\"\r\n");
      out.write("    \t        \t\t        \t  \r\n");
      out.write("    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("    \t    \t\t\t\t\t\t  $(\"#d_test1\").html(v_test1);\t\r\n");
      out.write("\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test2+=\"<form id='f_test2'>\"\r\n");
      out.write("    \t        \t\t        \t  v_test2+=jsonDoc[1].d_no+\". \"+jsonDoc[1].question+\"<br/><br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,2)'>\"+jsonDoc[1].answer1+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,2)'>\"+jsonDoc[1].answer2+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,2)'>\"+jsonDoc[1].answer3+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,2)'>\"+jsonDoc[1].answer4+\"<br/>\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test2+=\"</form>\"\r\n");
      out.write("    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("    \t    \t\t\t\t\t\t  $(\"#d_test2\").html(v_test2);\t\r\n");
      out.write("\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test3+=\"<form id='f_test3'>\"\r\n");
      out.write("    \t        \t\t        \t  v_test3+=jsonDoc[2].d_no+\". \"+jsonDoc[2].question+\"<br/><br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,3)'>\"+jsonDoc[2].answer1+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,3)'>\"+jsonDoc[2].answer2+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,3)'>\"+jsonDoc[2].answer3+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,3)'>\"+jsonDoc[2].answer4+\"<br/>\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test3+=\"</form>\"\r\n");
      out.write("    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("    \t    \t\t\t\t\t\t  $(\"#d_test3\").html(v_test3);\t\r\n");
      out.write("\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test4+=\"<form id='f_test4'>\"\r\n");
      out.write("    \t        \t\t        \t  v_test4+=jsonDoc[3].d_no+\". \"+jsonDoc[3].question+\"<br/><br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,4)'>\"+jsonDoc[3].answer1+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,4)'>\"+jsonDoc[3].answer2+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,4)'>\"+jsonDoc[3].answer3+\"<br/>\";\r\n");
      out.write("    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,4)'>\"+jsonDoc[3].answer4+\"<br/>\";\r\n");
      out.write("    \t    \t\t\t\t\t  \t  v_test4+=\"</form>\"\r\n");
      out.write("    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("    \t    \t\t\t\t\t\t  $(\"#d_test4\").html(v_test4);\t\r\n");
      out.write("    \t        \t\t           //}//for\r\n");
      out.write("    \t        \t\t       }\r\n");
      out.write("    \t        \t\t   }\t   \r\n");
      out.write("    \t        \t\t});\r\n");
      out.write("    \t        \t\t$(\"#dlg_test1\").dialog('open');      \t\t\t\t   \r\n");
      out.write("    \t\t\t   }\r\n");
      out.write("    \t\t\t   else if(\"응시불가\"==result){\r\n");
      out.write("    \t\t\t\t   $(\"#d_isOk\").html('<font color=\"red\">수험번호를 확인하세요.</font>');\r\n");
      out.write("    \t\t\t\t   return;\r\n");
      out.write("    \t\t\t   }\r\n");
      out.write("    \t\t   }\r\n");
      out.write("    \t\t});\r\n");
      out.write("\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction prev(p_test){\r\n");
      out.write("    \t\tif(p_test=='dlg_test2'){\r\n");
      out.write("    \t\t\t$(\"#dlg_test1\").dialog('open');\r\n");
      out.write("    \t\t\t$(\"#dlg_test2\").dialog('close');\r\n");
      out.write("    \t\t}    \t\t\r\n");
      out.write("    \t\telse if(p_test=='dlg_test3'){\r\n");
      out.write("    \t\t\t$(\"#dlg_test2\").dialog('open');\r\n");
      out.write("    \t\t\t$(\"#dlg_test3\").dialog('close');\r\n");
      out.write("    \t\t}    \t\t\r\n");
      out.write("    \t\telse if(p_test=='dlg_test4'){\r\n");
      out.write("    \t\t\t$(\"#dlg_test3\").dialog('open');\r\n");
      out.write("    \t\t\t$(\"#dlg_test4\").dialog('close');\r\n");
      out.write("    \t\t}    \t\t\r\n");
      out.write("    \t}\r\n");
      out.write("    \tfunction next(p_test){\r\n");
      out.write("\t\t\tvar dap1;\r\n");
      out.write("    \t\tif(p_test=='dlg_test1'){\r\n");
      out.write("        \t\ttemp1=1\r\n");
      out.write("        \t\tfor(var i=0;i<document.getElementById(\"f_test1\").cb.length;i++){\r\n");
      out.write("        \t\t\tif(document.getElementById(\"f_test1\").cb[i].checked==1){\r\n");
      out.write("        \t\t\t\tdap1 = temp1;\r\n");
      out.write("        \t\t\t}else{\r\n");
      out.write("        \t\t\t\ttemp1 = temp1 + 1;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t} \r\n");
      out.write("        \t\t$.cookie('c_test1', dap1, {expires: 1});\r\n");
      out.write("    \t\t\t$(\"#dlg_test1\").dialog('close');\r\n");
      out.write("    \t\t\t$(\"#dlg_test2\").dialog('open');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\telse if(p_test=='dlg_test2'){\r\n");
      out.write("    \t\t\talert(\"1번 답안:\"+$.cookie('c_test1'));\r\n");
      out.write("        \t\ttemp1=1\r\n");
      out.write("        \t\tfor(var i=0;i<document.getElementById(\"f_test2\").cb.length;i++){\r\n");
      out.write("        \t\t\tif(document.getElementById(\"f_test2\").cb[i].checked==1){\r\n");
      out.write("        \t\t\t\tdap1 = temp1;\r\n");
      out.write("        \t\t\t}else{\r\n");
      out.write("        \t\t\t\ttemp1 = temp1 + 1;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t} \r\n");
      out.write("        \t\t$.cookie('c_test2', dap1, {expires: 1});\r\n");
      out.write("    \t\t\t$(\"#dlg_test2\").dialog('close');\r\n");
      out.write("    \t\t\t$(\"#dlg_test3\").dialog('open');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\telse if(p_test=='dlg_test3'){\r\n");
      out.write("    \t\t\talert(\"2번 답안:\"+$.cookie('c_test2'));\r\n");
      out.write("        \t\ttemp1=1\r\n");
      out.write("        \t\tfor(var i=0;i<document.getElementById(\"f_test3\").cb.length;i++){\r\n");
      out.write("        \t\t\tif(document.getElementById(\"f_test3\").cb[i].checked==1){\r\n");
      out.write("        \t\t\t\tdap1 = temp1;\r\n");
      out.write("        \t\t\t}else{\r\n");
      out.write("        \t\t\t\ttemp1 = temp1 + 1;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t} \r\n");
      out.write("        \t\t$.cookie('c_test3', dap1, {expires: 1});    \t\t\t\r\n");
      out.write("    \t\t\t$(\"#dlg_test3\").dialog('close');\r\n");
      out.write("    \t\t\t$(\"#dlg_test4\").dialog('open');\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\telse if(p_test=='dlg_test4'){\r\n");
      out.write("    \t\t\talert(\"3번 답안:\"+$.cookie('c_test3'));\r\n");
      out.write("        \t\ttemp1=1\r\n");
      out.write("        \t\tfor(var i=0;i<document.getElementById(\"f_test4\").cb.length;i++){\r\n");
      out.write("        \t\t\tif(document.getElementById(\"f_test4\").cb[i].checked==1){\r\n");
      out.write("        \t\t\t\tdap1 = temp1;\r\n");
      out.write("        \t\t\t}else{\r\n");
      out.write("        \t\t\t\ttemp1 = temp1 + 1;\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t} \r\n");
      out.write("        \t\t$.cookie('c_test4', dap1, {expires: 1});      \t\t\t\r\n");
      out.write("    \t\t\t$(\"#dlg_test4\").dialog('close');\r\n");
      out.write("                $(\"#u_dap\").html(\"1번.\"+$.cookie('c_test1')+\" 2번.\"+$.cookie('c_test2')\r\n");
      out.write("        \t\t        +\" 3번.\"+$.cookie('c_test3')+\" 4번.\"+$.cookie('c_test4'));  \r\n");
      out.write("    \t\t\t$(\"#dlg_send\").dialog('open');    \t\t\t\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function (){\r\n");
      out.write("\t\t\t//$(\"#exam_no\").textbox('setValue','1907250008');\r\n");
      out.write("\t\t\t$(\"#exam_no\").textbox({\r\n");
      out.write("\t\t\t\tonChange:function(nval,oval){\r\n");
      out.write("\t\t\t\t\t//$(\"#d_isOk\").hide();\t\r\n");
      out.write("\t\t    \t\tvar u_exam_no = $(\"#exam_no\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t    \t\t$.ajax({\r\n");
      out.write("\t\t    \t\t\tmethod:\"get\"\r\n");
      out.write("\t\t    \t\t   ,url:\"isOk.kos?work=onLineTest&mem_id=");
      out.print(s_memid);
      out.write("&exam_no=\"+u_exam_no\r\n");
      out.write("\t\t    \t\t   ,success:function(result){\r\n");
      out.write("\t\t    \t\t\t   //alert(\"result: \"+result);\r\n");
      out.write("\t\t    \t\t\t   if(\"승인\"==result){\r\n");
      out.write("\t\t    \t        \t\t$.ajax({\r\n");
      out.write("\t\t    \t        \t\t\tmethod:\"get\"\r\n");
      out.write("\t\t    \t        \t\t   ,url:\"swDesignExam.kos?work=onLineTest&sub_cd=\"+g_subcd\r\n");
      out.write("\t\t    \t        \t\t   ,success:function(result){\r\n");
      out.write("\t\t    \t        \t\t\t   //alert(\"result:\"+result);\r\n");
      out.write("\t\t    \t        \t\t       //var result1 = JSON.stringify(result);\r\n");
      out.write("\t\t    \t        \t\t       var jsonDoc = JSON.parse(result);\r\n");
      out.write("\t\t    \t    /*     \t\t       var obj = JSON.parse(result, function(key, value){\r\n");
      out.write("\t\t    \t        \t\t    \t  if(key==\"question\"){\r\n");
      out.write("\t\t    \t        \t\t    \t\t  alert(\"key:\"+key+\", value:\"+value);\r\n");
      out.write("\t\t    \t        \t\t    \t  }else{\r\n");
      out.write("\t\t    \t        \t\t    \t\t  alert(\"없을 때\");\r\n");
      out.write("\t\t    \t        \t\t    \t  }\r\n");
      out.write("\t\t    \t        \t\t       }); */\r\n");
      out.write("\t\t    \t        \t\t       if(jsonDoc.length>0){//추천 테마 있음\r\n");
      out.write("\t\t    \t        \t\t       \t   //for(var i=0; i<jsonDoc.length; i++){\r\n");
      out.write("\t\t    \t        \t\t        \t  //alert(\"question:\"+jsonDoc[i].question+\", answer1:\"+jsonDoc[i].answer1);\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t    var v_test1 = \"\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t    var v_test2 = \"\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t    var v_test3 = \"\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t    var v_test4 = \"\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test1+=\"<form id='f_test1'>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test1+=jsonDoc[0].d_no+\". \"+jsonDoc[0].question+\"<br/><br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,1)'>\"+jsonDoc[0].answer1+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,1)'>\"+jsonDoc[0].answer2+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,1)'>\"+jsonDoc[0].answer3+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test1+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,1)'>\"+jsonDoc[0].answer4+\"<br/>\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test1+=\"</form>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  \r\n");
      out.write("\t\t    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("\t\t    \t    \t\t\t\t\t\t  $(\"#d_test1\").html(v_test1);\t\r\n");
      out.write("\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test2+=\"<form id='f_test2'>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test2+=jsonDoc[1].d_no+\". \"+jsonDoc[1].question+\"<br/><br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,2)'>\"+jsonDoc[1].answer1+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,2)'>\"+jsonDoc[1].answer2+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,2)'>\"+jsonDoc[1].answer3+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test2+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,2)'>\"+jsonDoc[1].answer4+\"<br/>\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test2+=\"</form>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("\t\t    \t    \t\t\t\t\t\t  $(\"#d_test2\").html(v_test2);\t\r\n");
      out.write("\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test3+=\"<form id='f_test3'>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test3+=jsonDoc[2].d_no+\". \"+jsonDoc[2].question+\"<br/><br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,3)'>\"+jsonDoc[2].answer1+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,3)'>\"+jsonDoc[2].answer2+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,3)'>\"+jsonDoc[2].answer3+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test3+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,3)'>\"+jsonDoc[2].answer4+\"<br/>\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test3+=\"</form>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("\t\t    \t    \t\t\t\t\t\t  $(\"#d_test3\").html(v_test3);\t\r\n");
      out.write("\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test4+=\"<form id='f_test4'>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test4+=jsonDoc[3].d_no+\". \"+jsonDoc[3].question+\"<br/><br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='1' onChange='answer(0,4)'>\"+jsonDoc[3].answer1+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='2' onChange='answer(1,4)'>\"+jsonDoc[3].answer2+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='3' onChange='answer(2,4)'>\"+jsonDoc[3].answer3+\"<br/>\";\r\n");
      out.write("\t\t    \t        \t\t        \t  v_test4+=\"&nbsp;&nbsp;&nbsp;<input type='checkbox' name='cb' value='4' onChange='answer(3,4)'>\"+jsonDoc[3].answer4+\"<br/>\";\r\n");
      out.write("\t\t    \t    \t\t\t\t\t  \t  v_test4+=\"</form>\"\r\n");
      out.write("\t\t    \t        \t\t        \t  //alert(v_test1);\r\n");
      out.write("\t\t    \t    \t\t\t\t\t\t  $(\"#d_test4\").html(v_test4);\t\r\n");
      out.write("\t\t    \t        \t\t           //}//for\r\n");
      out.write("\t\t    \t        \t\t       }\r\n");
      out.write("\t\t    \t        \t\t   }\t   \r\n");
      out.write("\t\t    \t        \t\t});\r\n");
      out.write("\t\t    \t        \t\t$(\"#dlg_test1\").dialog('open');      \t\t\t\t   \r\n");
      out.write("\t\t    \t\t\t   }\r\n");
      out.write("\t\t    \t\t\t   else if(\"응시불가\"==result){\r\n");
      out.write("\t\t    \t\t\t\t   $(\"#d_isOk\").html('<font color=\"red\">수험번호를 확인하세요.</font>');\r\n");
      out.write("\t\t    \t\t\t\t   return;\r\n");
      out.write("\t\t    \t\t\t   }\r\n");
      out.write("\t\t    \t\t   }\r\n");
      out.write("\t\t    \t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$('#cb_subject').combobox({\r\n");
      out.write("\t\t\t    url:'/onLineTest/subjectList.kos?work=onLineTest',\r\n");
      out.write("\t\t\t    valueField:'SUB_CD',\r\n");
      out.write("\t\t\t    textField:'SUB_NAME',\r\n");
      out.write("\t\t        onSelect: function(rec){\r\n");
      out.write("\t\t            g_subcd = rec.SUB_CD;\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t});\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("    <div style=\"margin:20px 0;\"></div>\r\n");
      out.write("    <div class=\"easyui-panel\" title=\"Test Takers\" style=\"width:100%;max-width:400px;padding:30px 60px;\">\r\n");
      out.write("    \t<form id=\"f_exam\">\r\n");
      out.write("    \t<input type=\"hidden\" id=\"work\" name=\"work\" value=\"onLineTest\">\r\n");
      out.write("        <div style=\"margin-bottom:20px\">\r\n");
      out.write("            <select class=\"easyui-combobox\" id=\"cb_subject\" label=\"수험과목선택:\" labelPosition=\"top\" data-options=\"prompt:'수험과목을 선택하세요'\" style=\"width:100%;\">\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"margin-bottom:20px\">\r\n");
      out.write("            <input class=\"easyui-textbox\" label=\"수험번호:\" id=\"exam_no\" name=\"exam_no\" labelPosition=\"top\" style=\"width:100%;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"javascript:examStart()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" style=\"width:100%;height:32px\">시험시작</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t</form>\r\n");
      out.write("    \t<div id=\"d_isOk\"></div>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- 시험 문제 1 -->\r\n");
      out.write("    <div id=\"dlg_test1\" class=\"easyui-dialog\" title=\"문제1\" style=\"width:700px;height:400px;padding:10px\"\r\n");
      out.write("            data-options=\"\r\n");
      out.write("                iconCls: 'icon-save',\r\n");
      out.write("                toolbar: '#dlg-toolbar',\r\n");
      out.write("                buttons: '#dlg-buttons',\r\n");
      out.write("                closed: 'true'\r\n");
      out.write("            \">\r\n");
      out.write("        <div id=\"d_test1\"></div>\r\n");
      out.write("    </div>      \r\n");
      out.write("        <div id=\"dlg-buttons\">\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:next('dlg_test1')\">다음문제</a>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- 시험 문제 2 -->\r\n");
      out.write("    <div id=\"dlg_test2\" class=\"easyui-dialog\" title=\"문제2\" style=\"width:700px;height:400px;padding:10px\"\r\n");
      out.write("            data-options=\"\r\n");
      out.write("                iconCls: 'icon-save',\r\n");
      out.write("                toolbar: '#dlg-toolbar',\r\n");
      out.write("                buttons: '#dlg-buttons',\r\n");
      out.write("                closed: 'true'\r\n");
      out.write("            \">\r\n");
      out.write("        <div id=\"d_test2\"></div>\r\n");
      out.write("    </div>      \r\n");
      out.write("        <div id=\"dlg-buttons\">\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:prev('dlg_test2')\">이전문제</a>\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:next('dlg_test2')\">다음문제</a>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- 시험 문제 3 -->\r\n");
      out.write("    <div id=\"dlg_test3\" class=\"easyui-dialog\" title=\"문제3\" style=\"width:700px;height:400px;padding:10px\"\r\n");
      out.write("            data-options=\"\r\n");
      out.write("                iconCls: 'icon-save',\r\n");
      out.write("                toolbar: '#dlg-toolbar',\r\n");
      out.write("                buttons: '#dlg-buttons',\r\n");
      out.write("                closed: 'true'\r\n");
      out.write("            \">\r\n");
      out.write("        <div id=\"d_test3\"></div>\r\n");
      out.write("    </div>      \r\n");
      out.write("        <div id=\"dlg-buttons\">\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:prev('dlg_test3')\">이전문제</a>\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:next('dlg_test3')\">다음문제</a>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- 시험 문제 4 -->\r\n");
      out.write("    <div id=\"dlg_test4\" class=\"easyui-dialog\" title=\"문제4\" style=\"width:700px;height:400px;padding:10px\"\r\n");
      out.write("            data-options=\"\r\n");
      out.write("                iconCls: 'icon-save',\r\n");
      out.write("                toolbar: '#dlg-toolbar',\r\n");
      out.write("                buttons: '#dlg-buttons',\r\n");
      out.write("                closed: 'true'\r\n");
      out.write("            \">\r\n");
      out.write("        <div id=\"d_test4\"></div>\r\n");
      out.write("    </div>      \r\n");
      out.write("        <div id=\"dlg-buttons\">\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:prev('dlg_test4')\">이전문제</a>\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:next('dlg_test4')\">제출하기</a>\r\n");
      out.write("    </div> \r\n");
      out.write("    <!-- 답안지 제출 하기 -->\r\n");
      out.write("    <div id=\"dlg_send\" class=\"easyui-dialog\" title=\"답안지 제출하기\" style=\"width:700px;height:400px;padding:10px\"\r\n");
      out.write("            data-options=\"\r\n");
      out.write("                iconCls: 'icon-save',\r\n");
      out.write("                toolbar: '#dlg-toolbar',\r\n");
      out.write("                buttons: '#dlg-buttons',\r\n");
      out.write("                closed: 'true'\r\n");
      out.write("            \">\r\n");
      out.write("        \t<div id=\"u_dap\"></div>\r\n");
      out.write("        \t<script>\r\n");
      out.write("      \t\r\n");
      out.write("        \t</script>\r\n");
      out.write("        \t<br>\r\n");
      out.write("        \t수고하셨습니다.<br>\r\n");
      out.write("        \t답안지 제출 버튼을 눌러 주세요.\r\n");
      out.write("    </div>      \r\n");
      out.write("        <div id=\"dlg-buttons\">\r\n");
      out.write("        <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=\"javascript:examSend()\">답안지제출</a>\r\n");
      out.write("    </div>     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
