/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-05-31 23:35:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/board/../common/easyui_common.jsp", Long.valueOf(1559345538162L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	List<Map<String,Object>> getBoardList = 
		(List<Map<String,Object>>)request.getAttribute("boardList");
	String rb_email = null;
	String rb_file = null;
	String rb_title = null;
	String rb_name = null;
	String rb_content = null;
	String rb_pwd = null;
	String rb_no = null;
	String rb_group = null;
	String rb_pos = null;
	String rb_step = null;
	if(getBoardList!=null && getBoardList.size()>0){
		rb_email = getBoardList.get(0).get("BM_EMAIL").toString();
		rb_file = getBoardList.get(0).get("BS_FILE").toString();
		rb_title = getBoardList.get(0).get("BM_TITLE").toString();
		rb_name = getBoardList.get(0).get("BM_WRITER").toString();
		rb_content = getBoardList.get(0).get("BM_CONTENT").toString();
		rb_pwd = getBoardList.get(0).get("BM_PW").toString();
		rb_no = getBoardList.get(0).get("BM_NO").toString();
		rb_group = getBoardList.get(0).get("BM_GROUP").toString();
		rb_pos = getBoardList.get(0).get("BM_POS").toString();
		rb_step = getBoardList.get(0).get("BM_STEP").toString();
	}
	

      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>글상세보기</title>\r\n");
      out.write("<!-- 공통 코드 include처리 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/commons.js\"></script>");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//글삭제하기 이벤트 처리\r\n");
      out.write("\tfunction boardDelView(){\r\n");
      out.write("\t\talert(\"boardDelView호출 성공\");\r\n");
      out.write("\t\t  $('#d_boardDel').dialog({\r\n");
      out.write("\t\t\t    title: '글삭제',\r\n");
      out.write("\t\t\t    buttons: btn_boardDel,\r\n");
      out.write("\t\t\t    width: 420,\r\n");
      out.write("\t\t\t    height: 250,\r\n");
      out.write("\t\t\t    closed: true,\r\n");
      out.write("\t\t\t    cache: false,\r\n");
      out.write("\t\t\t    href: 'boardDelForm.jsp?bm_no=");
      out.print(rb_no);
      out.write("&bm_pw=");
      out.print(rb_pwd);
      out.write("',\r\n");
      out.write("\t\t\t    modal: true\r\n");
      out.write("\t   }); \r\n");
      out.write("\t   $('#d_boardDel').dialog('open');\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t//글삭제 화면에서 확인 버튼을 클릭했을 때\r\n");
      out.write("\tfunction boardDel(){\r\n");
      out.write("\t\tvar db_pw = ");
      out.print(rb_pwd);
      out.write("\r\n");
      out.write("\t\tvar u_pw = $(\"#db_pw\").textbox('getValue');\r\n");
      out.write("\t\talert(\"db_pw:\"+db_pw+\", u_pw:\"+u_pw);\r\n");
      out.write("\t\t//alert(\"사용자가 입력한 비번:\"+$(\"#db_pw\").textbox('getValue'));\r\n");
      out.write("\t\t//사용자가 입력한 비번과 DB에서 읽어온 비번을 비교하여\r\n");
      out.write("\t\t//일치하면 삭제 처리 진행하고\r\n");
      out.write("\t\t//불일치하면 비번을 다시 입력받도록 해주세요.\r\n");
      out.write("\t\tif(u_pw==db_pw){\r\n");
      out.write("\t\t\t//alert(\"같다\");\r\n");
      out.write("\t\t\t$.messager.confirm('Confirm','정말 삭제하시겠습니까?',function(r){\r\n");
      out.write("\t\t\t //r:true-ok, false-cancel\r\n");
      out.write("\t\t\t\tif (r){//자바스크립트는 0이면 false 나머지 true\r\n");
      out.write("\t\t\t    \tlocation.href=\"./boardList.mvc?crud=del&b_no=");
      out.print(rb_no);
      out.write("&b_file=");
      out.print(rb_file);
      out.write("\";    \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#db_pw\").textbox('setValue','');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction boardDelClose(){\r\n");
      out.write("\t\t $('#d_boardDel').dialog('close');\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("    <table align=\"center\" id=\"p\" class=\"easyui-panel\" title=\"글상세보기\" \r\n");
      out.write("        style=\"width:670px;height:380px;padding:10px;background:#fafafa;\">\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>제목</td>\r\n");
      out.write("\t    \t<td><input id=\"bm_title\" value=\"");
      out.print(rb_title);
      out.write("\" name=\"bm_title\" data-options=\"width:'450px'\" class=\"easyui-textbox\"></td>\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>작성자</td>\r\n");
      out.write("\t    \t<td><input id=\"bm_writer\" value=\"");
      out.print(rb_name);
      out.write("\" name=\"bm_writer\" class=\"easyui-textbox\"></td>\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>이메일</td>\r\n");
      out.write("\t    \t<td><input id=\"bm_email\" value=\"");
      out.print(rb_email);
      out.write("\" name=\"bm_email\" class=\"easyui-textbox\"></td>\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>내용</td>\r\n");
      out.write("\t    \t<td><input id=\"bm_content\" value=\"");
      out.print(rb_content);
      out.write("\" name=\"bm_content\" data-options=\"multiline:'true', width:'570px', height:'90px'\" class=\"easyui-textbox\"></td>\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>비밀번호</td>\r\n");
      out.write("\t    \t<td><input id=\"bm_pw\" value=\"");
      out.print(rb_pwd);
      out.write("\" name=\"bm_pw\" class=\"easyui-passwordbox\"></td>\r\n");
      out.write("\t    \t</tr>\t    \t\r\n");
      out.write("\t   </table>\r\n");
      out.write("\t    <table align=\"center\">\r\n");
      out.write("\t    \t<tr>\r\n");
      out.write("\t    \t<td>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:repleForm('");
      out.print(rb_no);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(rb_group);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(rb_pos);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(rb_step);
      out.write("')\" class=\"easyui-linkbutton\">댓글</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:updateForm()\" class=\"easyui-linkbutton\">수정</a>\r\n");
      out.write("\t\t\t\t<a href=\"javascript:boardDelView()\" class=\"easyui-linkbutton\">삭제</a>\r\n");
      out.write("\t    \t</td>\r\n");
      out.write("\t    \t</tr>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t\t<!-- 글삭제 시작 -->\r\n");
      out.write("\t\t<div id=\"d_boardDel\" closed=\"true\" class=\"easyui-dialog\" style=\"padding:20px 50px\">\r\n");
      out.write("\t\t\t<div id=\"btn_boardDel\" align=\"right\">\r\n");
      out.write("\t\t\t<a href=\"javascript:boardDel()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" style=\"width:90px\">확인</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:boardDelClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" style=\"width:90px\">닫기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 글삭제  끝   -->\r\n");
      out.write("\t\t<!-- 글수정 시작 -->\r\n");
      out.write("\t\t<div id=\"d_boardUpd\" closed=\"true\" class=\"easyui-dialog\" style=\"padding:20px 50px\">\r\n");
      out.write("\t\t\t<div id=\"btn_boardUpd\" align=\"right\">\r\n");
      out.write("\t\t\t<a href=\"javascript:boardUpd()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" style=\"width:90px\">등록</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:boardUpdClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" style=\"width:90px\">닫기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 글수정  끝  -->\r\n");
      out.write("\t\t<!-- 댓글쓰기 시작 -->\r\n");
      out.write("\t\t<div id=\"d_boardReple\" closed=\"true\" class=\"easyui-dialog\" style=\"padding:20px 50px\">\r\n");
      out.write("\t\t\t<div id=\"btn_boardReple\" align=\"right\">\r\n");
      out.write("\t\t\t<a href=\"javascript:boardReple()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" style=\"width:90px\">등록</a>\r\n");
      out.write("\t\t\t<a href=\"javascript:boardRepleClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" style=\"width:90px\">닫기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 댓글쓰기  끝  -->\t    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
