/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-05-31 23:20:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.semanticUI;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/semanticUI/../common/easyui_common.jsp", Long.valueOf(1559344727547L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLDecoder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/semantic-ui@2.3.3/dist/semantic.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/demo/demo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/commons.js\"></script>");
      out.write('\r');
      out.write('\n');

	String smem_name = null;
	String sstatus = null;
	//주의사항 - 세션처리시 ClassCastException - 형전환을 잘못했을 경우 scnt- new Integer()
	String cnt = null;
	if(session.getAttribute("smem_name")!=null){
		smem_name = session.getAttribute("smem_name").toString();
	}
	if(session.getAttribute("sstatus")!=null){
		sstatus = session.getAttribute("sstatus").toString();
	}
	if(session.getAttribute("scnt")!=null){
		cnt = session.getAttribute("scnt").toString();
	}
	out.print("cnt:"+cnt);
	Cookie[] cs = request.getCookies();
	String c_value = null;
	String sunglass = null;
	String shortpants = null;
	String suncream = null;
	String shortshirts = null;
	String slipper = null;
	if(cs !=null && cs.length>0){//쿠키가 존재하니?
		for(int i=0;i<cs.length;i++){
			String c_name = cs[i].getName();
			if("JSESSIONID".equals(c_name)){
				c_value = cs[i].getValue();
			}
			else if("cmem_name".equals(c_name)){
				c_value = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			/* 상품 정보 조회 하기 시작 */
			else if(c_name=="sunglass"){
				sunglass = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			else if(c_name=="shortpants"){
				shortpants = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			else if(c_name=="suncream"){
				suncream = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			else if(c_name=="shortshirts"){
				shortshirts = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			else if(c_name=="slipper"){
				slipper = URLDecoder.decode(cs[i].getValue(),"utf-8");
			}
			/* 상품 정보 조회 하기  끝 */
		}	
	}///end of if
	//out.print(c_value);

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>시맨틱UI API활용</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$.noConflict();\r\n");
      out.write("\tvar J = jQuery; \r\n");
      out.write("\tvar status ='");
      out.print(c_value);
      out.write("';\r\n");
      out.write("\tvar cnt = 0;//5번 연속으로 비번 틀렸을 경우  카운트 값을 담을 변수\r\n");
      out.write("\tvar scnt = ");
      out.print(cnt);
      out.write(";\r\n");
      out.write("\tfunction pwSearch(){\r\n");
      out.write("\t\t//임시비번을 발급 받을 때 아이디 필요함 - 필수입력사항 - 유효성검사 처리\r\n");
      out.write("\t\tvar user_id = J(\"#mem_id\").val();\r\n");
      out.write("\t\tif(user_id==null || user_id.length==0){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\treturn;//pwSearch함수 탈출\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tvar param = \"gubun=pwSearch&user_id=\"+J(\"#mem_id\").val();\r\n");
      out.write("\t\t\tJ.ajax({\r\n");
      out.write("\t\t\t\tmethod:\"POST\",\r\n");
      out.write("\t\t\t\tdata:param,//user_id=사용자가 입력한 아이디\r\n");
      out.write("\t\t\t\turl:\"./member.kos\",//모델1으로 할것인지 , 모델2로 할것인지 결정하기\r\n");
      out.write("\t\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(xhrObject){\r\n");
      out.write("\t\t\t\t\talert(xhrObject.responseText);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction memoMgr(){\r\n");
      out.write("\t\tcmm_window_popup(\"./memberListTabs.jsp\",\"620\",\"400\",\"memberList\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction onLineTest(){\r\n");
      out.write("\t\tcmm_window_popup(\"../onLineTest/testForm1.html\",\"700\",\"450\",\"testForm1\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction cart(gName,gValue){\r\n");
      out.write("\t\tlocation.href=\"./cartAction.jsp?gName=\"+gName+\"&gValue=\"+gValue;\r\n");
      out.write("\t}\r\n");
      out.write("/* \tfunction cartList(){\r\n");
      out.write("\t\tcmm_window_popup(\"cartInfoList.jsp\",\"700\",\"450\",\"cartInfo\");\r\n");
      out.write("\t} */\r\n");
      out.write("\tfunction memberShip(){\r\n");
      out.write("\t\tcmm_window_popup(\"memberForm.jsp\",\"700\",\"450\",\"memberForm\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction loginCheck(){\r\n");
      out.write("\t\tif(status == 'null' || status.length==0){\r\n");
      out.write("\t\t\talert(\"로그인 하세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("    function logout(){\r\n");
      out.write("\t\tJ.ajax({\r\n");
      out.write("\t\t\tmethod:\"GET\",\r\n");
      out.write("//\t\t\turl:\"./logoutCookie.jsp\",\r\n");
      out.write("\t\t\turl:\"./logoutSession.jsp\",\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\tstatus = \"\";\r\n");
      out.write("\t\t\t\tJ(\"#mem_id\").val(\"\");\r\n");
      out.write("\t\t\t\tJ(\"#mem_pw\").val(\"\");\r\n");
      out.write("\t\t\t\tJ(\"#loginForm\").show();\r\n");
      out.write("\t\t\t\tJ(\"#logoutForm\").hide();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhrObject){\r\n");
      out.write("\t\t\t\talert(xhrObject.responseText);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});    \t\r\n");
      out.write("    }\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tvar x = document.cookie;\r\n");
      out.write("\t\t//alert(\"x:\"+x);\r\n");
      out.write("\t\tvar param = \"command=login&mem_id=\"+J(\"#mem_id\").val()+\"&mem_pw=\"+J(\"#mem_pw\").val();\r\n");
      out.write("\t\tJ.ajax({\r\n");
      out.write("\t\t\tmethod:\"POST\",\r\n");
      out.write("\t\t\turl:\"./member.kos?gubun=login\",\r\n");
      out.write("\t\t\tdata:param,\r\n");
      out.write("\t\t\tsuccess:function(result){\r\n");
      out.write("\t\t\t\t//조회결과를 담을 json포맷정보 출력 테스트\r\n");
      out.write("\t\t\t\t//document.write(result);\r\n");
      out.write("\t\t\t\tvar jsonDoc = JSON.parse(result);\r\n");
      out.write("  \t\t\t\tfor(var i=0;i<jsonDoc.length;i++){\r\n");
      out.write("  \t\t\t\t\tif(jsonDoc[i].cnt!=null){\r\n");
      out.write("  \t\t\t\t\t\tif(jsonDoc[i].cnt==5){\r\n");
      out.write("  \t\t\t\t\t\t\talert(\"캡챠서비스 이동\");\r\n");
      out.write("  \t\t\t\t\t\t\treturn;\r\n");
      out.write("  \t\t\t\t\t\t}\r\n");
      out.write("  \t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(-1==jsonDoc[i].sstatus){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디가 존재하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tJ(\"#loginForm\").show();\r\n");
      out.write("\t\t\t\t\t\tJ(\"#mem_id\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(0==jsonDoc[i].sstatus){\r\n");
      out.write("\t\t\t\t\t\talert(\"비번이 맞지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t\tcnt=cnt+1;\r\n");
      out.write("\t\t\t\t\t\tdocument.cookie = \"cnt=\"+cnt+\"; expires=\"+expires+\"; path=/\";\r\n");
      out.write("\t\t\t\t\t\tJ(\"#loginForm\").show();\r\n");
      out.write("\t\t\t\t\t\tJ(\"#mem_pw\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse if(1==jsonDoc[i].sstatus){\r\n");
      out.write("\t\t\t\t\t\tJ(\"#loginForm\").hide();\r\n");
      out.write("\t\t\t\t\t\tJ(\"#logoutForm\").show();\r\n");
      out.write("\t\t\t\t\t\tJ(\"#d_msg\").html(jsonDoc[i].smem_name+\"님 환영합니다.\");\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror:function(xhrObject){\r\n");
      out.write("\t\t\t\talert(xhrObject.responseText);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tif(scnt>0){\r\n");
      out.write("\t\talert(\"읽지 않은 쪽지가 \"+scnt+\"통 있습니다.\\n 확인버튼을 누르면 닫힘.\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- <body onLoad=\"cartList()\"> -->\r\n");
      out.write("\t<div class=\"ui inverted vertical masthead center aligned segment teal\">\r\n");
      out.write("\t\t<div class=\"ui text container\">\r\n");
      out.write("\t\t\t<h1 class=\"ui inverted header\">집나와</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"ui container\">\r\n");
      out.write("\t\t\t<div class=\"ui secondary  menu\">\r\n");
      out.write("\t\t\t\t<div class=\"left menu\">\r\n");
      out.write("\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui icon input\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"검색\"> <i class=\"search link icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 아이디와 비밀번호 -->\t\r\n");
      out.write("<!--======================[[ 로그인 화면 추가 시작 ]]=====================-->\t\t\r\n");
      out.write("\t\t\t\t<div id=\"loginForm\" class=\"item\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ui mini input\">\r\n");
      out.write("\t\t\t\t\t\t<input value='test' type=\"text\" id=\"mem_id\" name=\"mem_id\" placeholder=\"아이디\" style=\"margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<input value='123' type=\"text\" id=\"mem_pw\" name=\"mem_pw\" placeholder=\"비밀번호\" style=\"margin-right: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btn_login\" class=\"ui inverted white button\" style=\"margin-right: 10px;\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btn_pwSearch\" class=\"ui inverted white button\" onClick=\"pwSearch()\">비번찾기</button>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"btn_member\" class=\"ui inverted white button\" onClick=\"memberShip()\">회원가입</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--======================[[ 로그인 화면 추가   끝 ]]=====================-->\r\n");
      out.write("<!--======================[[ 로그아웃 화면 추가 시작 ]]=====================-->\t\t\r\n");
      out.write("\t\t\t\t<div id=\"logoutForm\" class=\"item\">\r\n");
      out.write("\t\t\t\t\t<div id=\"d_msg\"></div>\r\n");
      out.write("\t\t\t\t\t<button id=\"btn_logout\" class=\"ui inverted white button\" style=\"margin-right: 5px;\">로그아웃</button>\r\n");
      out.write("\t\t\t\t\t<button id=\"btn_memberUpd\" class=\"ui inverted white button\">정보수정</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--======================[[ 로그아웃 화면 추가 끝    ]]=====================-->\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"ui container\">\r\n");
      out.write("\t\t<div class=\"ui grid\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t<div class=\"four wide column\">\r\n");
      out.write("<!--======================[[ 사이드 메뉴 추가 시작 ]]=====================-->\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"ui vertical fluid tabular menu\" id=\"menu\">\r\n");
      out.write("\t\t\t\t\t<a id=\"m_intro\" class=\"item\">인트로 </a>\r\n");
      out.write("\t\t\t\t\t<a id=\"m_memo\" class=\"item\">쪽지관리 </a>\r\n");
      out.write("\t\t\t\t\t<a id=\"m_cart\" class=\"item\"> 장바구니 </a>\r\n");
      out.write("\t\t\t\t\t<a id=\"m_gmap\" class=\"item\"> 구글맵 </a>\r\n");
      out.write("\t\t\t\t\t<a id=\"m_ontest\" class=\"item\"> 온라인시험 </a>\r\n");
      out.write("\t\t\t\t\t<a id=\"m_board\" class=\"item\"> 게시판 </a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--======================[[ 사이드 메뉴 추가  끝   ]]=====================-->\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"twelve wide stretched column\">\r\n");
      out.write("<!--======================[[ 사이드 메뉴 본문 시작 ]]=====================-->\t\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"c_intro\" class=\"ui segment\">\r\n");
      out.write("\t\t\t\t인트로 페이지\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"c_cart\" class=\"ui segment\">\r\n");
      out.write("\t\t\t\t장바구니 서비스\r\n");
      out.write("\t\t\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t\t\t<tr><th>물품명</th><th>&nbsp;</th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><th>썬그라스</th><th><a href=\"javascript:cart('sunglass','썬그라스')\">장바구니담기</a></th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><th>반바지</th><th><a href=\"javascript:cart('shortpants','반바지')\">장바구니담기</a></th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><th>썬크림</th><th><a href=\"javascript:cart('suncream','썬크림')\">장바구니담기</a></th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><th>반팔티</th><th><a href=\"javascript:cart('shortshirts','반팔티')\">장바구니담기</a></th></tr>\r\n");
      out.write("\t\t\t\t\t<tr><th>슬리퍼</th><th><a href=\"javascript:cart('slipper','슬리퍼')\">장바구니담기</a></th></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"c_gmap\" class=\"ui segment\">\r\n");
      out.write("\t\t\t\t구글맵 서비스\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"c_ontest\" class=\"ui segment\">\r\n");
      out.write("\t\t\t\t온라인 시험 서비스\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"c_board\" class=\"ui segment\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("<!--======================[[ 사이드 메뉴 본문   끝  ]]=====================-->\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("/* 처음 실행했을 때 4개 내용이 다 보여요ㅜㅜ 어떡하지?  화면 초기화 처리가 필요해요 */\r\n");
      out.write("\t\tJ(document).ready(function(){\r\n");
      out.write("\t\t\tJ(\"#c_intro\").show();\r\n");
      out.write("\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write("\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write("\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write("\t\t\tJ(\"#c_board\").hide();\t\r\n");
      out.write("\t\t\tJ(\"#logoutForm\").hide();\r\n");
      out.write("\t\t\tJ(\"#btn_login\").click(function (){\r\n");
      out.write("\t\t\t\t//alert(\"로그인버튼 클릭시....\");\r\n");
      out.write("\t\t\t\tlogin();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tJ(\"#btn_logout\").click(function (){\r\n");
      out.write("\t\t\t\tlogout();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tJ('#menu').find('a').click(function() {\r\n");
      out.write("\t\t\tJ('#menu').find('a').attr('class', 'item');\r\n");
      out.write("\t\t\tJ(this).attr('class', 'item active');\r\n");
      out.write("\t\t\t//alert(J(this).attr('id'));\r\n");
      out.write("/* \t\t\tif(status == 'null' || status.length==0){\r\n");
      out.write("\t\t\t\talert(\"로그인 하세요\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} */\r\n");
      out.write(" \t\t\tif(J(this).attr('id')=='m_intro'){//인트로 선택한거니?\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").show();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(J(this).attr('id')=='m_cart'){//구글맵서비스가 필요해?\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").show();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").hide();\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(J(this).attr('id')=='m_gmap'){//구글맵서비스가 필요해?\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").show();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").hide();\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(J(this).attr('id')=='m_memo'){//쪽지관리화면이동할건데\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").hide();\t\r\n");
      out.write(" \t\t\t\tmemoMgr();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(J(this).attr('id')=='m_ontest'){//시험볼거니?\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").hide();\t\r\n");
      out.write(" \t\t\t\tonLineTest();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(J(this).attr('id')=='m_board'){//게시판 쓸건가?\r\n");
      out.write(" \t\t\t\tJ(\"#c_intro\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_cart\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_gmap\").hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_ontest\" ).hide();\r\n");
      out.write(" \t\t\t\tJ(\"#c_board\").show();\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
