package com.ch17;

/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-01-31 02:02:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class a_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {//서버에서 초기화를 담당-너는 잊어도 된다.
  }

  public void _jspDestroy() {//자원반납-너는 관여 안해도 괜찮아
  }
//내가 작성한 코드는 모두 다 service()안에 담김.
//내 안에 너(html) 있다.
//어떻게 했어? - out.print();-> oos.write(), oos.writeObject(), oos.writeInt()
  
  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String mem_id = "test";
	//문제 
	//a.jsp페이지에서 생성한 객체 mem_id를 b.jsp에서 사용하고 싶다 
	//어떡하지?

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<!-- \r\n");
      out.write("이 페이지를 실행해 봤나요?\r\n");
      out.write("무엇을 봤는지 말해 봅시다.\r\n");
      out.write("1)먼저 주소창에 a.jsp페이지를 요청함.\r\n");
      out.write("2)버튼을 클릭하면 b.jsp페이지로 이동함.\r\n");
      out.write("3)b.jsp페이지의 내용이 출력됨.\r\n");
      out.write("4)url이 변경되었음.\r\n");
      out.write("  :기존 요청이 끊어지고 새로운 요청이 발생함.\r\n");
      out.write("  :a.jsp페이지에서 담은 정보를 b.jsp페이지에서 사용할 수 없음.\r\n");
      out.write("  \r\n");
      out.write("이전 페이지로 이동하기\r\n");
      out.write("location.go(-1);\r\n");
      out.write("\r\n");
      out.write("다음 페이지로 이동하기\r\n");
      out.write("location.go(1);   \r\n");
      out.write(" -->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>a.jsp</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction move(){\r\n");
      out.write("/* \r\n");
      out.write(" * 자바코드와 자바스크립트는 형제관계인가? 아니면 남남인가? \r\n");
      out.write("   남남이라면 어떻게 코드를 같이 쓸 수 있는것인가?\t\r\n");
      out.write("*/\t\t\r\n");
      out.write("\t\tlocation.href=\"b.jsp?mem_id=");
 out.print(mem_id);
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction nextPage(){\r\n");
      out.write("\t\thistory.go(1);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("여기는 a.jsp<br>\r\n");
      out.write("<input type=\"button\" value=\"b.jsp이동\" onClick=\"move()\"> \r\n");
      out.write("<input type=\"button\" value=\"다음\" onClick=\"nextPage()\"> \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
